[versions]
ktor = "3.0.1"

[libraries]
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }

[bundles]
ktor-client = ["ktor-client-core", "ktor-client-java"]