[versions]
ktor = "3.0.1"

[libraries]
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }

[plugins]
gradle-publish = { id = "com.gradle.plugin-publish", version = "1.3.0" }
ktlint-gradle = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.1" }

[bundles]
ktor-client = ["ktor-client-core", "ktor-client-java"]